In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/crime-learn/crime_test.csv
/kaggle/input/crime-learn/sample_submission.csv
/kaggle/input/crime-learn/crime_train.csv


In [2]:
df= pd.read_csv('/kaggle/input/crime-learn/sample_submission.csv')
df

ID  Prediction
0      1           1
1      2           1
2      3           1
3      4           1
4      5           1
..   ...         ...
394  395           1
395  396           1
396  397           1
397  398           1
398  399           1

[399 rows x 2 columns]

In [3]:
test_data = pd.read_csv('/kaggle/input/crime-learn/crime_test.csv')
test_data

ID  population  householdsize  agePct12t21  agePct12t29  agePct16t24  \
0      1       11874           2.11        10.54        30.87        14.08   
1      2       14143           2.68        21.01        33.35        21.95   
2      3       34882           2.32        12.56        21.79        11.29   
3      4       29885           3.53        20.10        34.33        18.31   
4      5      935933           2.86        15.89        30.35        14.98   
..   ...         ...            ...          ...          ...          ...   
394  395       11096           2.40        26.67        47.49        36.51   
395  396       11843           2.45        12.77        24.08        11.09   
396  397       33892           2.80        16.81        28.88        13.91   
397  398       29060           2.76        15.46        27.15        12.78   
398  399       12567           2.51        13.03        20.15         9.21   

     agePct65up  numbUrban  pctUrban  medIncome  ...  MedRentPctHousInc  \
0          8.16      11874     100.0      30141  ...               22.9   
1         14.55          0       0.0      23886  ...               30.5   
2         19.51      34881     100.0      21053  ...               26.5   
3          8.18      29885     100.0      18956  ...               26.2   
4          9.50     935927     100.0      23584  ...               25.3   
..          ...        ...       ...        ...  ...                ...   
394       11.11          0       0.0      22265  ...               35.1   
395       15.82          0       0.0      21321  ...               25.9   
396       12.35      33892     100.0      19391  ...               25.0   
397        9.38      29060     100.0      33118  ...               23.0   
398       20.84          0       0.0      34255  ...               26.7   

     MedOwnCostPctInc  MedOwnCostPctIncNoMtg  NumInShelters  NumStreet  \
0                19.2                   11.4              2          1   
1                21.0                   14.9              0          0   
2                16.9                   11.8              0          9   
3                19.8                   13.8              0          0   
4                20.9                   12.7            698         44   
..                ...                    ...            ...        ...   
394              17.8                   11.9              0          0   
395              18.5                   15.5             12          0   
396              15.9                   12.8              0          5   
397              15.3                   12.4              2          0   
398              22.9                   11.0              0          0   

     PctForeignBorn  PctBornSameState  PctSameHouse85  PctSameCity85  \
0              7.02             51.78           39.89          75.63   
1              2.35             75.91           51.79          72.20   
2              1.61             74.43           62.60          86.35   
3             18.46             68.90           52.42          83.01   
4              9.35             69.25           51.62          83.78   
..              ...               ...             ...            ...   
394            6.50             42.07           36.22          47.90   
395            1.08             65.35           64.44          84.86   
396           11.56             60.92           66.23          92.98   
397            2.43             66.47           57.27          77.55   
398            3.18             12.95           39.77          65.91   

     PctSameState85  
0             83.39  
1             88.40  
2             90.85  
3             90.76  
4             90.95  
..              ...  
394           70.05  
395           89.83  
396           93.49  
397           92.13  
398           67.04  

[399 rows x 89 columns]

In [4]:
test_data.shape

(399, 89)

In [5]:
train_data = pd.read_csv('/kaggle/input/crime-learn/crime_train.csv')
train_data

ID  population  householdsize  agePct12t21  agePct12t29  agePct16t24  \
0        1       14985           2.56        16.55        34.42        22.54   
1        2       30843           2.83        15.45        35.12        18.14   
2        3       74991           2.52        10.48        20.43         9.11   
3        4       45061           2.44        10.59        24.97        11.61   
4        5       12863           2.45        12.02        22.51        10.49   
...    ...         ...            ...          ...          ...          ...   
1590  1591      372242           2.58        12.88        27.02        12.96   
1591  1592       49389           2.56        11.17        22.59        10.65   
1592  1593      131591           2.62        12.40        28.85        13.61   
1593  1594      165121           2.36        16.31        32.25        18.75   
1594  1595       30601           2.41        11.08        22.59        10.15   

      agePct65up  numbUrban  pctUrban  medIncome  ...  MedOwnCostPctInc  \
0          10.13          0       0.0      35545  ...              23.3   
1           4.70          0       0.0      32033  ...              21.6   
2          20.68      73342      97.8      31177  ...              23.6   
3          16.34      45061     100.0      39822  ...              24.0   
4          18.46          0       0.0      23044  ...              16.0   
...          ...        ...       ...        ...  ...               ...   
1590       10.63     372242     100.0      27095  ...              25.3   
1591       18.16      49389     100.0      41745  ...              22.4   
1592       11.28     131591     100.0      35103  ...              25.1   
1593       13.77     165121     100.0      19923  ...              20.4   
1594       16.17      30601     100.0      32002  ...              17.3   

      MedOwnCostPctIncNoMtg  NumInShelters  NumStreet  PctForeignBorn  \
0                      13.5              0          0            3.32   
1                      10.9             68         41            4.98   
2                      11.9              0          0            6.51   
3                      16.3              0          1           13.13   
4                      11.7              0          0            1.08   
...                     ...            ...        ...             ...   
1590                   12.8            431        303           19.75   
1591                   15.0              3          3            6.16   
1592                   11.8            220         14           27.53   
1593                   13.6            354        130            1.98   
1594                   11.4              0          0            1.08   

      PctBornSameState  PctSameHouse85  PctSameCity85  PctSameState85  \
0                60.94           47.28          66.65           82.41   
1                25.24           28.17          52.73           59.20   
2                13.69           34.49          60.88           66.97   
3                67.79           65.19          84.28           91.32   
4                80.22           53.17          86.56           93.15   
...                ...             ...            ...             ...   
1590             45.34           48.53          79.89           89.05   
1591             68.75           69.46          92.04           95.25   
1592             39.13           45.87          80.95           84.68   
1593             69.57           47.86          77.77           87.92   
1594             69.21           60.29          88.44           92.55   

      ViolentCrimesPerPop  
0                  428.64  
1                  742.54  
2                  303.72  
3                  373.88  
4                  108.07  
...                   ...  
1590              2601.60  
1591               199.45  
1592              1280.74  
1593              1693.42  
1594               271.52  

[1595 rows x 90 columns]

In [6]:
train_data.shape

(1595, 90)

In [7]:
test_data.corr()

ID  population  householdsize  agePct12t21  \
ID                1.000000   -0.104767       0.015711    -0.004221   
population       -0.104767    1.000000      -0.000866    -0.001917   
householdsize     0.015711   -0.000866       1.000000     0.495704   
agePct12t21      -0.004221   -0.001917       0.495704     1.000000   
agePct12t29      -0.000303    0.066482       0.365499     0.861744   
...                    ...         ...            ...          ...   
PctForeignBorn    0.018364    0.083432       0.381281    -0.050914   
PctBornSameState -0.030716   -0.030117      -0.069128     0.047258   
PctSameHouse85   -0.014207   -0.037796      -0.068009    -0.381894   
PctSameCity85    -0.054866    0.025825      -0.094316    -0.436794   
PctSameState85   -0.005691   -0.018532      -0.003121    -0.238510   

                  agePct12t29  agePct16t24  agePct65up  numbUrban  pctUrban  \
ID                  -0.000303    -0.009048   -0.022464  -0.104126  0.027082   
population           0.066482     0.021462   -0.070790   0.997396  0.169316   
householdsize        0.365499     0.304063   -0.581981  -0.000562  0.010109   
agePct12t21          0.861744     0.929751   -0.385649  -0.016971 -0.234682   
agePct12t29          1.000000     0.945955   -0.499119   0.057363 -0.108923   
...                       ...          ...         ...        ...       ...   
PctForeignBorn       0.089134    -0.009707   -0.135338   0.097627  0.236512   
PctBornSameState    -0.057110    -0.021282    0.066841  -0.043802 -0.242069   
PctSameHouse85      -0.549116    -0.459052    0.320150  -0.029787  0.070420   
PctSameCity85       -0.553242    -0.539531    0.264303   0.030583  0.032809   
PctSameState85      -0.379520    -0.343680    0.169868  -0.017225 -0.039900   

                  medIncome  ...  MedRentPctHousInc  MedOwnCostPctInc  \
ID                 0.024486  ...           0.015347          0.024978   
population        -0.084272  ...           0.109478          0.039741   
householdsize      0.217761  ...           0.094716          0.225054   
agePct12t21       -0.224847  ...           0.277197         -0.163375   
agePct12t29       -0.295280  ...           0.347678         -0.005524   
...                     ...  ...                ...               ...   
PctForeignBorn     0.132319  ...           0.284859          0.555599   
PctBornSameState  -0.163127  ...          -0.294662         -0.486147   
PctSameHouse85     0.273329  ...          -0.369183         -0.216003   
PctSameCity85      0.028646  ...          -0.340020         -0.233531   
PctSameState85     0.051208  ...          -0.231689         -0.223102   

                  MedOwnCostPctIncNoMtg  NumInShelters  NumStreet  \
ID                            -0.024859      -0.082121  -0.070398   
population                     0.007491       0.841531   0.682957   
householdsize                 -0.154485      -0.064403  -0.041820   
agePct12t21                   -0.104808      -0.006572  -0.038933   
agePct12t29                   -0.016560       0.053069   0.008342   
...                                 ...            ...        ...   
PctForeignBorn                 0.006539       0.007760   0.063786   
PctBornSameState               0.199198       0.013090  -0.054260   
PctSameHouse85                 0.299560      -0.014695  -0.055933   
PctSameCity85                  0.169595       0.035374  -0.016238   
PctSameState85                 0.159752      -0.002719  -0.030956   

                  PctForeignBorn  PctBornSameState  PctSameHouse85  \
ID                      0.018364         -0.030716       -0.014207   
population              0.083432         -0.030117       -0.037796   
householdsize           0.381281         -0.069128       -0.068009   
agePct12t21            -0.050914          0.047258       -0.381894   
agePct12t29             0.089134         -0.057110       -0.549116   
...                          ...               ...             ...   
PctForeignBorn          1.000000      

In [8]:
X_train =train_data.iloc[:,:-2].values
X_train

array([[1.00000e+00, 1.49850e+04, 2.56000e+00, ..., 6.09400e+01,
        4.72800e+01, 6.66500e+01],
       [2.00000e+00, 3.08430e+04, 2.83000e+00, ..., 2.52400e+01,
        2.81700e+01, 5.27300e+01],
       [3.00000e+00, 7.49910e+04, 2.52000e+00, ..., 1.36900e+01,
        3.44900e+01, 6.08800e+01],
       ...,
       [1.59300e+03, 1.31591e+05, 2.62000e+00, ..., 3.91300e+01,
        4.58700e+01, 8.09500e+01],
       [1.59400e+03, 1.65121e+05, 2.36000e+00, ..., 6.95700e+01,
        4.78600e+01, 7.77700e+01],
       [1.59500e+03, 3.06010e+04, 2.41000e+00, ..., 6.92100e+01,
        6.02900e+01, 8.84400e+01]])

In [9]:
y_train = train_data.iloc[:,-1].values
y_train

array([ 428.64,  742.54,  303.72, ..., 1280.74, 1693.42,  271.52])

In [10]:
X_test= test_data.iloc[:,:-1].values
X_test

array([[1.0000e+00, 1.1874e+04, 2.1100e+00, ..., 5.1780e+01, 3.9890e+01,
        7.5630e+01],
       [2.0000e+00, 1.4143e+04, 2.6800e+00, ..., 7.5910e+01, 5.1790e+01,
        7.2200e+01],
       [3.0000e+00, 3.4882e+04, 2.3200e+00, ..., 7.4430e+01, 6.2600e+01,
        8.6350e+01],
       ...,
       [3.9700e+02, 3.3892e+04, 2.8000e+00, ..., 6.0920e+01, 6.6230e+01,
        9.2980e+01],
       [3.9800e+02, 2.9060e+04, 2.7600e+00, ..., 6.6470e+01, 5.7270e+01,
        7.7550e+01],
       [3.9900e+02, 1.2567e+04, 2.5100e+00, ..., 1.2950e+01, 3.9770e+01,
        6.5910e+01]])

In [11]:
from sklearn.linear_model import LinearRegression  
reg = LinearRegression()
reg.fit(X_train, y_train)
reg.coef_

array([-2.58983167e-02,  5.98610368e-04,  3.93913680e+01, -8.25446307e+00,
       -3.56595899e+01,  3.27817328e+01, -1.27520193e+01, -7.50101583e-04,
        1.38179343e+00, -2.20463413e-02, -6.62454985e+00,  2.68934011e+01,
       -6.90920874e+00,  1.18473315e+01,  8.58442358e+00, -7.65771896e+00,
        1.70722804e-02, -3.84400452e-03, -2.66059903e-03, -2.51227056e+00,
       -1.37504018e+01,  4.61023933e+00,  1.84965883e+00, -1.28111753e+00,
        1.28149000e+01, -4.08394826e+00,  1.99262060e+00, -6.19188075e-01,
        4.27435541e+00,  1.97882720e+02, -2.14729832e+00,  1.41754966e+02,
       -3.29339509e+02, -3.73255314e+02, -1.63944528e+00, -1.98462830e+01,
        2.91682481e+00, -7.00164250e-01,  3.45151289e+00, -1.04893519e+01,
       -1.43173712e-03,  5.75012594e+01,  8.36675148e-04,  2.55842799e+00,
       -1.43752771e+00,  1.58655818e-01,  9.82441693e-01, -3.53232157e+01,
       -1.72835847e+01,  1.30885000e+01,  1.84165776e+00,  2.31627432e+00,
       -1.33284513e+01,  

In [12]:
reg.intercept_

985.6090486526531

In [13]:
reg.score(X_train, y_train)


0.6649581139874827

In [14]:
final = reg.predict(X_test)
final

array([ 791.05347807,  389.2285448 ,  660.24398449,  828.81886148,
       1053.66922174,  233.4682354 , 1181.34741922,  163.72565941,
       1422.74025878,  911.81126132,  259.42587742,  410.96090468,
        127.79470024,  293.75960716, 1074.83624409, 1333.90056718,
        798.81067516,  343.47970167, 1387.86053642, 1646.12929397,
        394.13073964,  415.0757241 , 1066.4688928 ,  100.79716059,
        927.20105761,  201.5808683 , 1073.32841725,  668.545465  ,
        415.18085922,  344.20240243,  266.56206749,  319.02458967,
        194.89471739,  478.68957185,  411.4518414 ,   68.81397486,
        155.55005587,  316.12604764,  972.61585052,   20.45571705,
        -62.18508602, 1500.00801139,  188.66345565,  437.15464998,
       1068.28285869,   93.58719305,  618.25416085,  175.04355294,
        825.56535623,  222.71063765,  852.68223452,  452.48032262,
        970.74695553,  652.73046139, -120.36337551,  578.80599581,
       1252.89429068,  342.04479386,   89.29352757,  769.03272

In [15]:
final_output = pd.DataFrame({'ID':test_data['ID'],'Prediction':np.array(final)})

In [16]:
final_output.to_csv("crime_final_output.csv")